// Mocks generated by Mockito 5.1.0 from annotations
// in api_study/test/movie_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:api_study/global/data/remote/i_http_service.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponse_0<T> extends _i1.Fake implements _i2.Response<T> {}

/// A class which mocks [IHttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHttpService extends _i1.Mock implements _i3.IHttpService {
  MockIHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> get(String? url,
          {Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
          Invocation.method(#get, [url], {#queryParameters: queryParameters}),
          returnValue: Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>())) as _i4
          .Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> post(String? url,
          {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#post, [url], {#body: body}),
              returnValue: Future<_i2.Response<dynamic>>.value(
                  _FakeResponse_0<dynamic>()))
          as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> put(String? url,
          {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#put, [url], {#body: body}),
              returnValue: Future<_i2.Response<dynamic>>.value(
                  _FakeResponse_0<dynamic>()))
          as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> patch(String? url,
          {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#patch, [url], {#body: body}),
              returnValue: Future<_i2.Response<dynamic>>.value(
                  _FakeResponse_0<dynamic>()))
          as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> delete(String? url,
          {Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #delete, [url], {#queryParameters: queryParameters}),
              returnValue: Future<_i2.Response<dynamic>>.value(
                  _FakeResponse_0<dynamic>()))
          as _i4.Future<_i2.Response<dynamic>>);
}
